#! /bin/python3
from npsocket import SocketNumpyArray
import numpy as np

sock_sender = SocketNumpyArray()
sock_sender.initialize_sender('localhost', 9999)

i=1
while True:
    frame = np.ones((480, 640))*i
    i=i+1
    print (i)
    sock_sender.send_numpy_array(frame)